on: [pull_request]

env:
  JWT_SECRET: 'secret'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instala o nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instala as dependências
        run: npm install

      - name: Executa o lint para verificar se há erros
        run: npx eslint ./src --ext .ts

  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instala as dependências
        run: npm install

      - name: Report test coverage
        uses: PoorlyDefinedBehaviour/nyc-reporter@v1
        with:
          command: "npm test"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}