on: [pull_request]

env:
  JWT_SECRET: 'secret'

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instala o nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instala as dependências
        run: npm install

      - name: Executa o lint para verificar se há erros
        run: npx eslint ./src --ext .ts

  test_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v2

      - name: Instala o NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Instala as dependências
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run coverage
        uses: Tintef/nyc-reporter-action@0.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORTER: 'text' # defaults to 'text-summary'